services:
  - type: web
    name: wireshop-backend
    env: node
    rootDir: wireshop-backend
    buildCommand: npm ci
    startCommand: npm start
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
    healthCheckPath: /health

  - type: static_site
    name: wireshop-frontend
    rootDir: wireshop-frontend
    buildCommand: ""
    staticPublishPath: .
    plan: free
    autoDeploy: true
    routes:
      - type: rewrite
        source: /api/*
        destination: https://wireshop-backend.onrender.com/api/:splat
